# Tensors

<ul>
  <li>similar to numpy arrays (but more suitable for deep learning)</li>
  <li>A  tensor is a multidimensional matrix containing elements of a single data type</li>
</ul>

In [4]:
import torch
import numpy as np

In [5]:
# regular list 
my_list = [[1,2,3,4,5],[6,7,8,9]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

In [6]:
# np array
np1 = np.random.rand(3,4)
np1

array([[0.14634361, 0.99068094, 0.78702752, 0.57654591],
       [0.05910128, 0.7967949 , 0.42021288, 0.59305153],
       [0.78154178, 0.60551146, 0.86452891, 0.6480836 ]])

In [7]:
np1.dtype

dtype('float64')

In [11]:
# Tensors
tensor_2d = torch.randn(3,4)
tensor_2d
# tensor_2d.dtype


torch.float32

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
## create tensor out of np array
my_torch = torch.tensor(np1)
my_torch 

tensor([[0.1463, 0.9907, 0.7870, 0.5765],
        [0.0591, 0.7968, 0.4202, 0.5931],
        [0.7815, 0.6055, 0.8645, 0.6481]], dtype=torch.float64)

# Tensor Operations
<ul>
  <li>reshape</li>
  <li>view</li>
  <li>slice</li>
</ul>

In [12]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# reshape and view
my_torch2 = my_torch2.reshape(2,5)
my_torch2


tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
# reshape if we dont know the number of items using -1
my_torch3 = torch.arange(15)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
my_torch3 = my_torch3.reshape(3,-1)
my_torch3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [30]:
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
my_torch5 = my_torch4.view(2,5)
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [33]:
# with reshape and view thwy will "update"
my_torch6 =torch.arange(10)
my_torch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
my_torch7 = my_torch6.reshape(2,5)
my_torch7

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [35]:
my_torch6[1] = 4141
my_torch6

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [36]:
my_torch6 # note that it has been updated because we used view / reshape

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [37]:
# slices allow us to grab a section of a tensor
my_torch8 = torch.arange(10)
my_torch8

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
# grabs a specific item
my_torch8[7]

tensor(7)

In [39]:
# grab a slice
my_torch9 = my_torch8.reshape(5,2)
my_torch9


tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [40]:
# we're taking the first column
my_torch9[:,1]


tensor([1, 3, 5, 7, 9])

In [41]:
# return column
my_torch9[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

# Tensor Math operations
<ul>
  <li>Add, subtract, multiply, divide, remainder, exponents</li>
  <li>shorthand and longhand</li>
  <li>re-assignments</li>

</ul>

In [43]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [44]:
# addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [45]:
# addition longhand (same effect as the above)
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [47]:
# subtract 
tensor_b - tensor_a


tensor([4, 4, 4, 4])

In [49]:
# sub function
torch.sub(tensor_b,- tensor_a)

tensor([ 6,  8, 10, 12])

In [50]:
# multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [52]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [53]:
# division
tensor_b / tensor_a # output is converted to float

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [54]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [55]:
# remainders, modulus
tensor_b % tensor_a # returns a list of remainders

tensor([0, 0, 1, 0])

In [56]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [57]:
# exponents,  or power
torch.pow(tensor_a, tensor_b )

tensor([    1,    64,  2187, 65536])

In [58]:
# another way of doing addition / calculations
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [59]:
tensor_a

tensor([1, 2, 3, 4])

In [60]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b) # this updates the value of tensor_a by using the underscore _

tensor([ 6,  8, 10, 12])

In [61]:
tensor_a

tensor([ 6,  8, 10, 12])